import schedule
import time
import os

os.system("A:\CAPSTONE\CODES\bengaluruHT.py")
os.system("A:\CAPSTONE\CODES\bengaluruNIE.py")
os.system("A:\CAPSTONE\CODES\bengaluruTH.py")
os.system("A:/CAPSTONE/CODES/bengaluruTOI.py")
os.system("A:/CAPSTONE/CODES/chandigarhHT.py")
os.system("A:/CAPSTONE/CODES/chandigarhTIE.py")
os.system("A:/CAPSTONE/CODES/chandigarhTOI.py")
os.system("A:/CAPSTONE/CODES/delhiHT.py")
os.system("A:/CAPSTONE/CODES/delhiNIE.py")
os.system("A:/CAPSTONE/CODES/delhiTH.py")
os.system("A:/CAPSTONE/CODES/delhiTOI.py")
os.system('A:/CAPSTONE/CODES/gurugramHT.py')
os.system('A:/CAPSTONE/CODES/gurugramTOI.py')
os.system("A:/CAPSTONE/CODES/hyderabadNIE.py")
os.system("A:/CAPSTONE/CODES/hyderabadTH.py")
os.system("A:/CAPSTONE/CODES/hyderabadTOI.py")
os.system("A:/CAPSTONE/CODES/kolkataHT.py")
os.system("A:/CAPSTONE/CODES/kolkataNIE.py")
os.system("A:/CAPSTONE/CODES/kolkataTH.py")
os.system("A:/CAPSTONE/CODES/kolkataTOI.py")
os.system("A:/CAPSTONE/CODES/mumbaiHT.py")
os.system("A:/CAPSTONE/CODES/mumbaiNIE.py")
os.system("A:/CAPSTONE/CODES/mumbaiTH.py")
os.system("A:/CAPSTONE/CODES/mumbaiTOI.py")
os.system("A:/CAPSTONE/CODES/puneHT.py")
os.system("A:/CAPSTONE/CODES/puneTOI.py")